const exchangeActionsType = {
    CURRENT_EXCHANGE_INFO: "CURRENT_EXCHANGE_INFO",
    FETCH_FAILED: "FETCH_FAILED",
    FETCH_REQUESTED: "FETCH_REQUESTED",
    USER_ENTER_NEW_EXCHANGE_INFO: "USER_ENTER_NEW_EXCHANGE_INFO",
    USER_ENTER_NEW_EXCHANGE_INFO_SALE: "USER_ENTER_NEW_EXCHANGE_INFO_SALE"
}

export default exchangeActionsType